"""message_id 去唯一，改用平台组合索引（OneBot 12 迁移 M2）

OneBot 12 的 message_id 为字符串且各平台不保证全局唯一；
messages.message_id 的 unique 约束改为普通索引，
并新增 (platform, message_id, created_at) 组合索引。

Revision ID: af82430887b7
Revises: eebc4752a3af
Create Date: 2026-08-18 10:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af82430887b7"
down_revision: str | None = "eebc4752a3af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_message_id"))
        batch_op.create_index(batch_op.f("ix_messages_message_id"), ["message_id"], unique=False)
        batch_op.add_column(
            sa.Column("platform", sa.String(), server_default="onebot", nullable=False)
        )
        batch_op.create_index(
            "ix_messages_platform_message_id_created_at",
            ["platform", "message_id", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_platform_message_id_created_at")
        batch_op.drop_column("platform")
        batch_op.drop_index(batch_op.f("ix_messages_message_id"))
        batch_op.create_index(batch_op.f("ix_messages_message_id"), ["message_id"], unique=True)

    # ### end Alembic commands ###
