"""make message_id unique

Revision ID: eebc4752a3af
Revises: f951883bf18c
Create Date: 2026-08-17 22:01:19.434997

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eebc4752a3af"
down_revision: str | None = "f951883bf18c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_message_id"))
        batch_op.create_index(batch_op.f("ix_messages_message_id"), ["message_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_message_id"))
        batch_op.create_index(batch_op.f("ix_messages_message_id"), ["message_id"], unique=False)

    # ### end Alembic commands ###
